# Linux Build and Publish on Itch.io
# Only run when pushed to main

name: Linux
on:
  push:
    branches: main
    paths:
      - '.github/workflows/linux.yml' # Deploy linux only when required
    
permissions:
  contents: read

jobs:
  build-linux:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: ubuntu-20.04
    
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }} # Needs to be added through github
      PROJECT_NAME: space-c
      PROJECT_BUILD_PATH: build_linux_x64
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_linux_x64
      PROJECT_CUSTOM_FLAGS: ""
      PROJECT_RESOURCES_PATH: resources

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Cache build/_deps
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/${{env.PROJECT_BUILD_PATH}}/_deps
          key: ${{env.PROJECT_BUILD_PATH}}-deps
          restore-keys: ${{env.PROJECT_BUILD_PATH}}-deps

      - name: Setup Environment
        run: | 
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev cmake
          mkdir -p ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_RESOURCES_PATH }}
        shell: bash

      - name: Configure Project
        run: |
          BUILD_TYPE=Release make configure

      - name: Build Project
        run: |
          make build PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE PROJECT_CUSTOM_FLAGS=${{ env.PROJECT_CUSTOM_FLAGS }}
      
      - name: Generate Artifacts
        run: |
          ls ${{ env.PROJECT_BUILD_PATH }}
          cp -r ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }} ${{ env.PROJECT_RELEASE_PATH }}
          cp README.md ${{ env.PROJECT_RELEASE_PATH }}
          cp LICENSE ${{ env.PROJECT_RELEASE_PATH }}
          ls ${{ env.PROJECT_RELEASE_PATH }}
          7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_RELEASE_PATH }}.zip
          path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

      - name: Download + Authorize Butler
        run: |
            curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
            unzip butler.zip
            chmod +x butler
            ./butler -V

      - name: Login To Butler
        run: ./butler login

      - name: Push Linux to Itch
        run: ./butler push ${{ env.PROJECT_RELEASE_PATH }} maiconspas/space-c:linux